FROM debian:buster as build-slim
LABEL maintainer="ric@ngd.io"

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
    groff \
    less \
    curl \
    unzip 

RUN ARCH=`uname -m` && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-$ARCH.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip &&\
    ./aws/install --bin-dir /aws-cli-bin &&\
    mkdir /cfg

# Now copy it into our base image.
FROM busybox:glibc

# Copy Core libs

COPY --from=build-slim /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=build-slim /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
COPY --from=build-slim /lib/x86_64-linux-gnu/libutil.so.1 /lib/x86_64-linux-gnu/libutil.so.1
COPY --from=build-slim /lib/x86_64-linux-gnu/librt.so.1 /lib/x86_64-linux-gnu/librt.so.1

# Copy aws tooling and directories

COPY --from=build-slim /usr/local/aws-cli /usr/local/aws-cli
COPY --from=build-slim /aws-cli-bin /usr/local/bin
COPY --from=build-slim /cfg /cfg

RUN adduser -D -u 1000 awsuser && \
    aws --version > /version

WORKDIR /cfg
ENV HOME=/home/awsuser
USER awsuser

ENTRYPOINT ["/usr/local/bin/aws"]
